import type { Metadata } from "next";
import "./globals.css";
import ReduxProviderWrapper from "@/store/redux-provider/ReduxProviderWrapper";
import { Toaster } from "sonner";

// app/layout.tsx
import { Inter, Playfair_Display, UnifrakturCook } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const playfair = Playfair_Display({ subsets: ["latin"], variable: "--font-playfair" });
const unifraktur = UnifrakturCook({ subsets: ["latin"], weight: "700", variable: "--font-cursive" });


export const metadata: Metadata = {
  title: "The Australian Canvas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${playfair.variable} ${unifraktur.variable}`}>
      <body>
        <body className="antialiased">
          <ReduxProviderWrapper>{children}</ReduxProviderWrapper>
          <Toaster />
        </body>
      </body>
    </html>
  );
}
