export const LANGUAGES = [
  { code: "af", label: "Afrikaans", flag: "za" },
  { code: "sq", label: "Albanian", flag: "al" },
  { code: "am", label: "Amharic", flag: "et" },
  { code: "ar", label: "Arabic", flag: "sa" },
  { code: "hy", label: "Armenian", flag: "am" },
  { code: "az", label: "Azerbaijani", flag: "az" },
  { code: "eu", label: "Basque", flag: "es" },
  { code: "be", label: "Belarusian", flag: "by" },
  { code: "bn", label: "Bengali", flag: "bd" },
  { code: "bs", label: "Bosnian", flag: "ba" },
  { code: "bg", label: "Bulgarian", flag: "bg" },
  { code: "ca", label: "Catalan", flag: "es" },
  { code: "ceb", label: "Cebuano", flag: "ph" },
  { code: "ny", label: "Chichewa", flag: "mw" },
  { code: "zh-CN", label: "Chinese (Simplified)", flag: "cn" },
  { code: "zh-TW", label: "Chinese (Traditional)", flag: "tw" },
  { code: "co", label: "Corsican", flag: "fr" },
  { code: "hr", label: "Croatian", flag: "hr" },
  { code: "cs", label: "Czech", flag: "cz" },
  { code: "da", label: "Danish", flag: "dk" },
  { code: "nl", label: "Dutch", flag: "nl" },
  { code: "en", label: "English", flag: "gb" },
  { code: "eo", label: "Esperanto", flag: "eu" }, // no country, using EU flag
  { code: "et", label: "Estonian", flag: "ee" },
  { code: "tl", label: "Filipino", flag: "ph" },
  { code: "fi", label: "Finnish", flag: "fi" },
  { code: "fr", label: "French", flag: "fr" },
  { code: "fy", label: "Frisian", flag: "nl" },
  { code: "gl", label: "Galician", flag: "es" },
  { code: "ka", label: "Georgian", flag: "ge" },
  { code: "de", label: "German", flag: "de" },
  { code: "el", label: "Greek", flag: "gr" },
  { code: "gu", label: "Gujarati", flag: "in" },
  { code: "ht", label: "Haitian Creole", flag: "ht" },
  { code: "ha", label: "Hausa", flag: "ng" },
  { code: "haw", label: "Hawaiian", flag: "us" },
  { code: "he", label: "Hebrew", flag: "il" },
  { code: "hi", label: "Hindi", flag: "in" },
  { code: "hmn", label: "Hmong", flag: "cn" },
  { code: "hu", label: "Hungarian", flag: "hu" },
  { code: "is", label: "Icelandic", flag: "is" },
  { code: "ig", label: "Igbo", flag: "ng" },
  { code: "id", label: "Indonesian", flag: "id" },
  { code: "ga", label: "Irish", flag: "ie" },
  { code: "it", label: "Italian", flag: "it" },
  { code: "ja", label: "Japanese", flag: "jp" },
  { code: "jw", label: "Javanese", flag: "id" },
  { code: "kn", label: "Kannada", flag: "in" },
  { code: "kk", label: "Kazakh", flag: "kz" },
  { code: "km", label: "Khmer", flag: "kh" },
  { code: "rw", label: "Kinyarwanda", flag: "rw" },
  { code: "ko", label: "Korean", flag: "kr" },
  { code: "ku", label: "Kurdish (Kurmanji)", flag: "iq" },
  { code: "ky", label: "Kyrgyz", flag: "kg" },
  { code: "lo", label: "Lao", flag: "la" },
  { code: "la", label: "Latin", flag: "va" }, // Vatican as symbolic
  { code: "lv", label: "Latvian", flag: "lv" },
  { code: "lt", label: "Lithuanian", flag: "lt" },
  { code: "lb", label: "Luxembourgish", flag: "lu" },
  { code: "mk", label: "Macedonian", flag: "mk" },
  { code: "mg", label: "Malagasy", flag: "mg" },
  { code: "ms", label: "Malay", flag: "my" },
  { code: "ml", label: "Malayalam", flag: "in" },
  { code: "mt", label: "Maltese", flag: "mt" },
  { code: "mi", label: "Maori", flag: "nz" },
  { code: "mr", label: "Marathi", flag: "in" },
  { code: "mn", label: "Mongolian", flag: "mn" },
  { code: "my", label: "Myanmar (Burmese)", flag: "mm" },
  { code: "ne", label: "Nepali", flag: "np" },
  { code: "no", label: "Norwegian", flag: "no" },
  { code: "or", label: "Odia (Oriya)", flag: "in" },
  { code: "ps", label: "Pashto", flag: "af" },
  { code: "fa", label: "Persian", flag: "ir" },
  { code: "pl", label: "Polish", flag: "pl" },
  { code: "pt", label: "Portuguese", flag: "pt" },
  { code: "pa", label: "Punjabi", flag: "in" },
  { code: "ro", label: "Romanian", flag: "ro" },
  { code: "ru", label: "Russian", flag: "ru" },
  { code: "sm", label: "Samoan", flag: "ws" },
  { code: "gd", label: "Scots Gaelic", flag: "gb-sct" },
  { code: "sr", label: "Serbian", flag: "rs" },
  { code: "st", label: "Sesotho", flag: "ls" },
  { code: "sn", label: "Shona", flag: "zw" },
  { code: "sd", label: "Sindhi", flag: "pk" },
  { code: "si", label: "Sinhala", flag: "lk" },
  { code: "sk", label: "Slovak", flag: "sk" },
  { code: "sl", label: "Slovenian", flag: "si" },
  { code: "so", label: "Somali", flag: "so" },
  { code: "es", label: "Spanish", flag: "es" },
  { code: "su", label: "Sundanese", flag: "id" },
  { code: "sw", label: "Swahili", flag: "ke" },
  { code: "sv", label: "Swedish", flag: "se" },
  { code: "tg", label: "Tajik", flag: "tj" },
  { code: "ta", label: "Tamil", flag: "in" },
  { code: "tt", label: "Tatar", flag: "ru" },
  { code: "te", label: "Telugu", flag: "in" },
  { code: "th", label: "Thai", flag: "th" },
  { code: "tr", label: "Turkish", flag: "tr" },
  { code: "tk", label: "Turkmen", flag: "tm" },
  { code: "uk", label: "Ukrainian", flag: "ua" },
  { code: "ur", label: "Urdu", flag: "pk" },
  { code: "ug", label: "Uyghur", flag: "cn" },
  { code: "uz", label: "Uzbek", flag: "uz" },
  { code: "vi", label: "Vietnamese", flag: "vn" },
  { code: "cy", label: "Welsh", flag: "gb-wls" }, // Wales
  { code: "xh", label: "Xhosa", flag: "za" },
  { code: "yi", label: "Yiddish", flag: "il" },
  { code: "yo", label: "Yoruba", flag: "ng" },
  { code: "zu", label: "Zulu", flag: "za" },
];
